#!/usr/bin/env python
import os
import re
import sys
import glob
import tempfile
import subprocess
import requests


def run(cmd):
    return subprocess.run(cmd, shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE).returncode

def get_sub(url):
    # firstly, try to download subs directly
    saved_path = os.getcwd()
    with tempfile.TemporaryDirectory() as work_path:
        os.chdir(work_path)
        run(f'yt-dlp --write-sub --convert-subs srt --skip-download "{url}" -o output')
        subs = glob.glob('*.srt')
        if len(subs) != 0:
            file = subs[0]
            run("sed -r '/^[0-9]+$/{n;d}' " + file + " > text")
            with open('text', 'r') as f:
                text = f.read()
        else:
            run(f'yt-dlp -f "wa" -x --audio-format mp3 "{url}" -o output')
            run("ffmpeg -i output.mp3 -acodec pcm_s16le -ar 16000 output.wav")
            run("whisper-cpp -m /storage/whisper/ggml-medium.bin -l auto -f output.wav -otxt -of text")
        with open('text.txt', 'r') as f:
            text = f.read()

    os.chdir(saved_path)
    return text


def usage():
    print('Usage: condense URL')

def main():
    if len(sys.argv) != 2:
        usage()
        exit()

    url = sys.argv[1]
    sub = get_sub(url)
    print(sub)

if __name__ == '__main__':
    main()


