#!/usr/bin/env bash

spaces (){
    hyprctl workspaces -j | jq -Mc 'map({id: .id, windows: .windows}) | sort_by(.id)'
    cur=$(hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id' | cat)
    floating=$(hyprctl clients -j |jq -r " .[] | select ( .workspace.id==$cur and .floating==false)" |wc -l)
    if [ $floating -eq 0 ]; then
        eww update bar_bg_color="background: transparent;"
    else
        eww update bar_bg_color="background: @theme_bg_color;"
    fi
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
