#!/usr/bin/env bash

# usage: import-gsettings
config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
if [ ! -f "$config" ]; then exit 1; fi

gnome_schema="org.gnome.desktop.interface"
gtk_theme="$(grep 'gtk-theme-name' "$config" | sed 's/.*\s*=\s*//')"
icon_theme="$(grep 'gtk-icon-theme-name' "$config" | sed 's/.*\s*=\s*//')"
cursor_theme="$(grep 'gtk-cursor-theme-name' "$config" | sed 's/.*\s*=\s*//')"
font_name="$(grep 'gtk-font-name' "$config" | sed 's/.*\s*=\s*//')"

echo "* {all: unset}" > ~/.config/gtk-4.0/gtk.css
echo "@import url(\"/etc/profiles/per-user/nixos/share/themes/$gtk_theme/gtk-4.0/gtk.css\");" >> ~/.config/gtk-4.0/gtk.css

gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" font-name "$font_name"

kthm_path="$(nix eval --raw nixpkgs#kitty-themes.outPath)"
echo $gtk_theme | grep -qi 'Darkest'
darkest=$?
if [ "$darkest" -eq 0 ]; then
    echo "include $kthm_path/share/kitty-themes/themes/Campbell.conf">~/.config/kitty/theme
else
    echo $gtk_theme | grep -qi 'Dark'
    dark=$?
    if [ "$dark" -eq 0 ]; then
        echo "include $kthm_path/share/kitty-themes/themes/Alucard.conf">~/.config/kitty/theme
    else
        echo $gtk_theme | grep -qi 'Light'
        light=$?
        if [ "$light" -eq 0 ]; then
            echo "include $kthm_path/share/kitty-themes/themes/Tomorrow.conf">~/.config/kitty/theme
        fi
    fi
fi
echo background $(grep -o "[^_]bg_color:[\#a-z0-9]*" /etc/profiles/per-user/nixos/share/themes/`grep -o "Flat[a-zA-Z\-]*" ~/.gtkrc-2.0`/gtk-2.0/gtkrc|sed "s/[^_]bg_color://")>>~/.config/kitty/theme

pkill -SIGUSR1 kitty
echo $gtk_theme | grep -qi 'Dark' && echo 'dark'>~/.darkmode || echo 'light'>~/.darkmode
pkill -SIGUSR1 nvim
setwp
